# Generate env file from command line arguments
# Generic rule - can be used by any platform (ESP, simulator, etc.)

def _make_env_file_impl(ctx):
    """Generate env file from --define and --action_env."""
    out = ctx.actions.declare_file(ctx.attr.name + ".env")
    
    # Static lines from --define (always emit all fields, use defaults or empty string)
    static_lines = []
    for key in ctx.attr.defines:
        value = ctx.var.get(key, "")
        if not value:
            value = ctx.attr.defaults.get(key, "")
        static_lines.append('{}="{}"'.format(key, value))
    
    # If no env_vars, just write static content
    if not ctx.attr.env_vars:
        lines = ["# Generated by make_env_file", ""]
        lines.extend(static_lines)
        ctx.actions.write(out, "\n".join(lines) + "\n")
    else:
        # Need shell to read environment variables
        env_var_lines = []
        for key in ctx.attr.env_vars:
            env_var_lines.append('echo "{}=\\"${{{}}}\\"" >> "$1"'.format(key, key))
        
        script = """
cat > "$1" << 'STATICEOF'
# Generated by make_env_file
{static}
STATICEOF
{env_cmds}
""".format(
            static = "\n".join(static_lines),
            env_cmds = "\n".join(env_var_lines),
        )
        
        ctx.actions.run_shell(
            outputs = [out],
            command = script,
            arguments = [out.path],
            use_default_shell_env = True,
        )
    
    return [DefaultInfo(files = depset([out]))]

make_env_file = rule(
    implementation = _make_env_file_impl,
    attrs = {
        "defines": attr.string_list(
            default = [],
            doc = "Variable names to read from --define",
        ),
        "env_vars": attr.string_list(
            default = [],
            doc = "Variable names to read from --action_env (shell environment)",
        ),
        "defaults": attr.string_dict(
            default = {},
            doc = "Default values when --define not provided",
        ),
    },
    doc = """Generate env file from --define and environment variables.
    
    Example:
    ```
    make_env_file(
        name = "env",
        defines = ["WIFI_SSID"],
        env_vars = ["WIFI_PASSWORD"],  # From shell env
    )
    ```
    
    Usage:
    ```bash
    # --define for explicit values
    # --action_env to pass shell environment variables
    WIFI_PASSWORD=secret bazel build //app \\
        --define WIFI_SSID=MyWiFi \\
        --action_env=WIFI_PASSWORD
    ```
    """,
)
