name: Setup ESP-IDF
description: Install ESP-IDF (via ESP-ADF) for cross-compiling ESP32 targets.
runs:
  using: "composite"
  steps:
    - shell: bash
      run: sudo apt-get update && sudo apt-get install -y git python3-pip cmake
    - shell: bash
      run: |
        sudo git clone --filter=blob:none --no-checkout \
          https://github.com/espressif/esp-adf.git \
          /usr/local/src/esp-adf
        cd /usr/local/src/esp-adf
        sudo git checkout 715aa221a37c43a92d3ceed6af1452ce4a50abdb
        sudo git submodule update --init --recursive --depth=1
        sudo chown -R runner:sudo /usr/local/src/esp-adf
    - shell: bash
      working-directory: /usr/local/src/esp-adf/esp-idf
      run: |
        . ./tools/detect_python.sh
        "${ESP_PYTHON}" ./tools/python_version_checker.py
        "${ESP_PYTHON}" ./tools/idf_tools.py --non-interactive install required --targets=all
        "${ESP_PYTHON}" ./tools/idf_tools.py --non-interactive install cmake
        "${ESP_PYTHON}" ./tools/idf_tools.py --non-interactive install-python-env
