//! H106 Assets — RGB565 image data loaded via @embedFile
//!
//! Format: u16 LE width + u16 LE height + row-major RGB565 pixels
//! Generated by tools/img2rgb565 from PNG source files.

const ui = @import("ui_state");
const Image = ui.Image;

/// Load an RGB565 image from embedded binary data.
/// Data format: [0:2] width LE, [2:4] height LE, [4:] RGB565 pixels LE
fn loadRgb565(comptime data: []const u8) Image {
    const w: u16 = @as(u16, data[0]) | (@as(u16, data[1]) << 8);
    const h: u16 = @as(u16, data[2]) | (@as(u16, data[3]) << 8);
    return .{
        .width = w,
        .height = h,
        .data = data[4..],
        .bytes_per_pixel = 2,
    };
}

// Background (240x240)
pub const bg = loadRgb565(@embedFile("assets/bg.rgb565"));

// Desktop standby (240x240)
pub const ultraman = loadRgb565(@embedFile("assets/ultraman.rgb565"));

// Menu carousel items (160x160 each)
pub const menu_items = [5]Image{
    loadRgb565(@embedFile("assets/menu_item0.rgb565")), // 奥特集结
    loadRgb565(@embedFile("assets/menu_item1.rgb565")), // 超能驯化
    loadRgb565(@embedFile("assets/menu_item2.rgb565")), // 守护联络
    loadRgb565(@embedFile("assets/menu_item3.rgb565")), // 积分
    loadRgb565(@embedFile("assets/menu_item4.rgb565")), // 设置
};

pub const MENU_LABELS = [5][]const u8{
    "Team",
    "Game",
    "Contact",
    "Points",
    "Settings",
};
